### ISSUE TITLE
ListenWebSocketClient.start failed

### ISSUE THREAD

**Issue by spencerchubb** [deepgram/deepgram-python-sdk#493]
## What is the current behavior?
```
def init_deepgram():
    def on_message(self, result, **kwargs):
        print("on_message")
        sentence = result.channel.alternatives[0].transcript
        if len(sentence) == 0:
            return
        print(f"Deepgram transcription: {sentence}")

    def on_error(self, error, **kwargs):
        print(f"Deepgram error: {error}")

    config = DeepgramClientOptions(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        options={"keepalive": "true"},
    )
    deepgram = DeepgramClient(config)
    dg_connection = deepgram.listen.websocket.v("1")
    dg_connection.on(LiveTranscriptionEvents.Transcript, on_message)
    dg_connection.on(LiveTranscriptionEvents.Error, on_error)

    options = LiveOptions(
        punctuate=True,
        language="en-US",
        vad_events=True,
    )
    return dg_connection.start(options)

init_deepgram()
```

```
WebSocketException in AbstractSyncWebSocketClient.start: server rejected WebSocket connection: HTTP 401
ListenWebSocketClient.start failed
```

## Expected behavior
I expect it to open the websocket connection successfully

## Please tell us about your environment
OS: WSL 2, Ubuntu
Python version: Python 3.10.12
deepgram-sdk 3.7.7
websockets 13.1

## Anything else we should know
I know that I'm populating the API key correctly because I tried printing it out

**Comment by spencerchubb** [comment]
I found a workaround for the above issue, but found what seems to be another bug

I had to pass in the api key to DeepgramClient. It did NOT work if I pass in api key to DeepgramClientOptions

**Comment by muazhari** [comment]
i have this bug too, any updates?

**Comment by lukeocodes** [comment]
Resolved in later versions

**Comment by phamkhactu** [comment]
I still have an error with example code in docs. Please check it again! 

**Version: 5.3.2**

```
Caught: server rejected WebSocket connection: HTTP 401
```


Code:
```
import threading
import time
import os
from dotenv import load_dotenv

load_dotenv()

from deepgram import DeepgramClient
from deepgram.core.events import EventType
from deepgram.extensions.types.sockets import ListenV2SocketClientResponse

api_key = os.getenv("DEEPGRAM_API_KEY")

client = DeepgramClient(access_token=api_key)


try:
    with client.listen.v2.connect(
        model="flux-general-en", encoding="linear16", sample_rate="16000"
    ) as connection:

        def on_message(message: ListenV2SocketClientResponse) -> None:
            msg_type = getattr(message, "type", "Unknown")
            print(f"Received {msg_type} event")

        connection.on(EventType.OPEN, lambda _: print("Connection opened"))
        connection.on(EventType.MESSAGE, on_message)
        connection.on(EventType.CLOSE, lambda _: print("Connection closed"))
        connection.on(EventType.ERROR, lambda error: print(f"Caught: {error}"))

        # EXAMPLE ONLY: Start listening in a background thread for demo purposes
        # In production, you would typically call connection.start_listening() directly
        # which blocks until the connection closes, or integrate into your async event loop
        threading.Thread(target=connection.start_listening, daemon=True).start()
        time.sleep(3)  # EXAMPLE ONLY: Wait briefly to see some events before exiting
except Exception as e:
    print(f"Caught: {e}")

```
